// SPEC-rung2-fill-c § 2: the probe's summary (Markdown) over every run file in a directory (bin/probe-counts.mjs writes
// both). Generated: it states what the runs found and nothing more; what it means for fill C is the contract's to say.
import { percentile } from "./probe-analysis.mjs";

const WIDTHS = [1280, 390];
const spacingLabel = (r) => (r.spacing === "gap" ? `gap ${r.gapMs} ms` : r.spacing === "nowait" ? "no wait" : "ack");
const ms = (v) => (v === null || v === undefined ? "—" : String(Math.round(v)));
const stats = (values) => [percentile(values, 50), percentile(values, 95), values.length ? Math.max(...values) : null].map(ms);
const full = (r) => !r.error && r.final && r.final.counted === r.need && r.final.items === `${r.need} items`;
const madeOf = (runs) => runs.flatMap((r) => r.presses.filter((p) => p.pressed));
const code = (s) => `\`${String(s).replace(/`/g, "'")}\``;

/** One row of the acknowledgement table: the card's own count. */
function ackRow(width, label, runs) {
  const made = madeOf(runs);
  const acked = made.filter((p) => p.acknowledged);
  const [med, p95, max] = stats(acked.map((p) => p.card.ackMs));
  const backs = runs.reduce((n, r) => n + r.takeBacks.length, 0);
  return `| ${width} | ${label} | ${runs.length} | ${made.length} | ${acked.length} | ${made.length - acked.length} | ${med} | ${p95} | ${max} | ${backs} | ${runs.filter(full).length} of ${runs.length} |`;
}

/** median / p95 / max (n) of one signal's latency over the presses that showed it. */
function signal(runs, pick) {
  const values = madeOf(runs).map(pick).filter((v) => v !== null && v !== undefined);
  const [med, p95, max] = stats(values);
  return `${med} / ${p95} / ${max} (${values.length})`;
}

/** Distinct values of a key over runs, numbers folded to N with the range seen ("N items" 1–14). */
function seen(runs, match, fold = true) {
  const out = new Map();
  for (const r of runs) {
    for (const c of r.changes) {
      if (!match(c.k) || c.v === null) continue;
      const key = fold ? c.v.replace(/\d+/g, "N") : c.v;
      const nums = (c.v.match(/\d+/g) ?? []).map(Number);
      const e = out.get(key) ?? { min: Infinity, max: -Infinity };
      for (const n of nums) {
        e.min = Math.min(e.min, n);
        e.max = Math.max(e.max, n);
      }
      out.set(key, e);
    }
  }
  if (!out.size) return "never present";
  return [...out].map(([k, e]) => `${code(k.replace(/\|/g, " · "))}${fold && e.min !== Infinity ? ` (N ${e.min === e.max ? e.min : `${e.min}–${e.max}`})` : ""}`).join("<br>");
}

export function renderSummary(runs, { command = null } = {}) {
  const sorted = [...runs].sort((a, b) => a.at.localeCompare(b.at));
  const ok = sorted.filter((r) => !r.error || r.presses.length);
  const releases = [...new Set(sorted.map((r) => r.release ?? "unknown"))];
  const first = sorted[0];
  const lines = [];
  lines.push("# The store's count, probed (SPEC-rung2-fill-c § 2)", "");
  lines.push(
    `Generated by \`tools/storefront-watch/bin/probe-counts.mjs\` from the ${sorted.length} run files beside it; re-running the probe into this directory rewrites it. ` +
      `Runs from ${first?.at ?? "—"} to ${sorted.at(-1)?.at ?? "—"} (UTC), on ${first ? code(first.origin + first.path) : "—"} with **no \`#fitaf=\` fragment**, ` +
      `${first?.need ?? "—"} meals a run, each in a fresh profile. The store's release${releases.length > 1 ? "s" : ""}: ${releases.map(code).join(", ")}.`,
  );
  if (command) lines.push("", `Command: ${code(command)}`);
  lines.push(
    "",
    "Nothing was pressed but each chosen meal's Add to Cart (a `.click()` on the store's own button, as fill B presses it); nothing typed; " +
      "no CHECKOUT pressed; /checkout never loaded.",
    "",
    "## Acknowledgement: from each press to the pressed card's own count",
    "",
    `The card's count: the pressed meal's ${code("app-product-card")} showing ${code("app-counter .counter")} with ${code(".counter__value")} 1 and no Add to Cart. ` +
      "Read every 50 ms from the page's own clock " +
      `(the longest gap between two reads in any run: ${ms(Math.max(0, ...sorted.map((r) => r.sampling?.maxGapMs ?? 0)))} ms), so a time is good to the next read; ` +
      "a count already shown when the press's `.click()` returned counts as the press's own duration. " +
      "Median, p95 (nearest rank) and max are over the presses acknowledged within 5 s. " +
      "Spacing: `ack`, the next press once the card shows its count (or after 5 s); `gap 200 ms`, fill B's spacing before rung 2 § 23; `no wait`, the next press as soon as the last returned. " +
      "Take-backs: any count that went down (below).",
    "",
    "| width | spacing | runs | presses | acknowledged ≤ 5 s | not acknowledged within 5 s | median ms | p95 ms | max ms | take-backs | plan full at the end |",
    "|---|---|---|---|---|---|---|---|---|---|---|",
  );
  for (const width of WIDTHS) {
    const byWidth = ok.filter((r) => r.width === width);
    if (!byWidth.length) continue;
    const labels = [...new Set(byWidth.map(spacingLabel))];
    for (const label of labels) lines.push(ackRow(width, label, byWidth.filter((r) => spacingLabel(r) === label)));
    if (labels.length > 1) lines.push(ackRow(width, "**all**", byWidth));
  }
  lines.push(
    "",
    "## The other counts: from each press until each showed it",
    "",
    "median / p95 / max ms (presses that showed it). The phone card is `app-product-card-mobile`'s counter (displayed at 390, hidden at 1280); the sidebar row is the meal's `app-cart-product-card` in `app-cart` (displayed at 1280, hidden at 390); " +
      "\"N items\" and the phone's \"Items\" are timed until they first read at least the press's own number (1 for the first press, 14 for the fourteenth).",
    "",
    "| width | spacing | the card (as above) | the phone card | the sidebar row | \"N items\" reaches the press's number | the phone's \"Items\" reaches it |",
    "|---|---|---|---|---|---|---|",
  );
  for (const width of WIDTHS) {
    const byWidth = ok.filter((r) => r.width === width);
    for (const label of [...new Set(byWidth.map(spacingLabel))]) {
      const rs = byWidth.filter((r) => spacingLabel(r) === label);
      lines.push(`| ${width} | ${label} | ${signal(rs, (p) => p.card.ackMs)} | ${signal(rs, (p) => p.mobile.ackMs)} | ${signal(rs, (p) => p.row.ackMs)} | ${signal(rs, (p) => p.items.reachedMs)} | ${signal(rs, (p) => p.phoneItems.reachedMs)} |`);
    }
  }
  lines.push(
    "",
    "## Take-backs, over-counts and glitches",
    "",
    "A take-back is a count that went down between two reads: a card, phone card or sidebar row from a count back to Add to Cart (or absent), " +
      "or the plan's \"N items\", the phone's \"Items\" or the pending list's count decreasing. ⚠ The plan's totals can hide one: a take-back in the " +
      "same 50 ms as another meal's count leaves the total unchanged (found on the synthetic store); the card's own count does not.",
    "",
  );
  const backs = sorted.flatMap((r) => r.takeBacks.map((t) => ({ r, t })));
  if (!backs.length) lines.push("**No count went down in any run**: no card, phone card or sidebar row went from a count back to Add to Cart, and no \"N items\", \"Items\" or pending count decreased.");
  for (const { r, t } of backs) {
    lines.push(`- ${r.width} ${spacingLabel(r)} (${r.at}): ${t.key}${t.meal ? ` of **${t.meal}** (press ${t.index + 1})` : ""}, ${code(t.from)} → ${code(t.to)} at ${ms(t.t)} ms after the first press${t.sinceAckMs !== null ? `, ${ms(t.sinceAckMs)} ms after its count showed` : ""}`);
  }
  const overs = sorted.flatMap((r) => (r.overCounts ?? []).map((o) => ({ r, o })));
  lines.push("", overs.length ? `Over-counts (a card above 1): ${overs.map(({ r, o }) => `${r.width} ${spacingLabel(r)} **${o.meal}** ${code(o.value)} at ${ms(o.t)} ms`).join("; ")}.` : "No card ever showed more than 1.");
  const glitches = sorted.flatMap((r) => r.glitches.map((g) => ({ r, g })));
  lines.push("", glitches.length ? `Glitches (a counted card read as neither a count nor Add to Cart): ${glitches.map(({ r, g }) => `${r.width} ${spacingLabel(r)} ${g.key} of **${g.meal}** ${code(g.from)} → ${code(g.to)} at ${ms(g.t)} ms`).join("; ")}.` : "No glitches: a counted card never read as anything but its count.");
  lines.push(
    "",
    "## What the store shows: selectors and texts",
    "",
    "Texts as read (whitespace collapsed), numbers folded to N with the range seen; a button as `text · enabled|disabled · shown|hidden`.",
    "",
    "| what | selector | 1280 | 390 |",
    "|---|---|---|---|",
  );
  const s = first?.selectors ?? {};
  const rowsOf = [
    ["the card's count (fill B's card)", `${s.card} ${s.cardActions} ${s.counter} ${s.counterValue}; − ${s.counterDecrease}, + ${s.counterIncrease}`, (k) => k.startsWith("card.")],
    ["the phone card's count", `${s.mobileCard} ${s.mobileActions} ${s.counter} ${s.counterValue}`, (k) => k.startsWith("mcard.")],
    ["the sidebar's row for the meal", `${s.sidebarRow} (by ${s.sidebarRowTitle}) ${s.counterValue}`, (k) => k.startsWith("row.")],
    ["the plan's \"N items\"", s.itemsCount, (k) => k === "items"],
    ["the phone's \"Items\"", `${s.phoneItems} (label "Items") ${s.phoneItemsValue}`, (k) => k === "phoneItems"],
    ["\"Please add at least M meals to continue\"", s.progressLabel, (k) => k === "progressLabel"],
    ["CHECKOUT, the sidebar (1025 px and wider)", s.sideCheckout, (k) => k === "side"],
    ["CHECKOUT, the phone bar", s.barCheckout, (k) => k === "bar"],
    ["the store's pending list (its count)", `localStorage ${s.pendingKey}`, (k) => k === "pending"],
    ["toasts on the page (how many)", s.toast, (k) => k === "toasts"],
  ];
  for (const [what, selector, match] of rowsOf) {
    const cell = (width) => seen(ok.filter((r) => r.width === width), match);
    lines.push(`| ${what} | ${code(selector)} | ${cell(1280)} | ${cell(390)} |`);
  }
  lines.push(
    "",
    "## Runs",
    "",
    "| file | at (UTC) | width | spacing | release | acknowledged ≤ 5 s | counted at the end (card · phone card · row) | \"N items\" at the end | CHECKOUT at the end | our console lines | page errors | error |",
    "|---|---|---|---|---|---|---|---|---|---|---|---|",
  );
  for (const r of sorted) {
    const made = r.presses.filter((p) => p.pressed);
    const f = r.final;
    const checkout = f ? [f.side, f.bar].filter((b) => b && b.shown).map((b) => `${b.text} (${b.disabled ? "disabled" : "enabled"})`).join("; ") || "none shown" : "—";
    lines.push(
      `| ${r.file ?? "—"} | ${r.at} | ${r.width} | ${spacingLabel(r)} | ${r.release ?? "—"} | ${made.filter((p) => p.acknowledged).length} of ${made.length} | ` +
        `${f ? `${f.counted} · ${f.countedMobile} · ${f.countedRows} of ${r.need}` : "—"} | ${f?.items ?? "—"} | ${checkout} | ${r.fitafLines.length} | ${r.pageErrors.length} | ${r.error ?? ""} |`,
    );
  }
  return `${lines.join("\n")}\n`;
}
